name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Build Docker image
        run: |
          docker build -t weather-app:latest .
      - name: Load Docker image into Minikube
        run: |
            minikube image load weather-app:latest
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml
      - name: Notify Deployment Status
        if: ${{ failure() }}
        run: echo "Deployment failed" || echo "Deployment successful"
