name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Install dependencies
        run: npm install
      - name: Fix permissions
        run: chmod +x ./node_modules/.bin/jest  
      - name: Run tests
        run: npm test

  build-and-deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Install Minikube
      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/

      # Start Minikube
      - name: Start Minikube
        run: |
          minikube start --driver=docker

      # Set up Docker environment for Minikube
      - name: Set up Docker environment for Minikube
        run: |
          eval $(minikube -p minikube docker-env)

      # Build Docker image
      - name: Build Docker image
        run: |
          docker build -t weather-app:latest .

      # Load Docker image into Minikube
      - name: Load Docker image into Minikube
        run: |
          minikube image load weather-app:latest

      # Install kubectl (Kubernetes CLI)
      - name: Install kubectl
        run: |
          curl -LO "https://storage.googleapis.com/kubernetes-release/release/v1.24.0/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      # Deploy to Kubernetes
      - name: Deploy to Kubernetes
        run: |
          kubectl apply -f k8s/deployment.yaml

      # Notify Deployment Status
      - name: Notify Deployment Status
        run: |
          if [[ $? -eq 0 ]]; then
            echo "Deployment successful"
          else
            echo "Deployment failed"
            exit 1
          fi
      - name: Get Minikube service URL
        run: |
            minikube service weather-app-service  
